### ISSUE TITLE
TemplateAssertionError, not sure what happens

### ISSUE THREAD

**Issue by ghost** [picotrading/ansible-grafana#3]
I met this error, but I can not figure out what happens, could you please help check?

TASK: [grafana | Configure Grafana] ******************************************\* 
fatal: [grafana02.rti.iot] => {'msg': "TemplateAssertionError: no test named 'mapping'", 'failed': True}
fatal: [grafana02.rti.iot] => {'msg': "TemplateAssertionError: no test named 'mapping'", 'failed': True}

the site.yml should be:
- hosts: monitorserver
  roles:
  - role: yumrepo
    # Configure the grafana YUM repo
    yumrepo_repos:
      grafana:
        name: Grafana repo
        baseurl: https://packagecloud.io/grafana/stable/el/6/x86_64
        gpgcheck: 0
  - role: grafana
    # Allow grafana to bind to TCP port <1024
    grafana_allow_low_port: false
    # Changing port nunmber from the default 3000 to 80
    grafana_server_http_port: 3000

**Comment by jtyr** [comment]
The same error was reported here:
https://github.com/picotrading/config-encoder-macros/issues/1

Please update your jinja2 and the problem should disappear.

**Comment by ghost** [comment]
it works!! thanks a lot for your quick response
