### ISSUE TITLE
AnsibleError: file: grafana.ini.j2

### ISSUE THREAD

**Issue by hgfranco** [picotrading/ansible-grafana#4]
I'm getting the following error when running the ansible-grafana role. I'm assuming that `ini_encode_macro.j2` should be located in the template directory? Which it isn't.

`TASK: [jtyr.grafana | Configure Grafana] **************************************
fatal: [servername.com] => {'msg': 'AnsibleError: file: /ansible/roles/jtyr.grafana/templates/grafana.ini.j2, error: Cannot find/not allowed to load (include) template templates/encoder/macros/ini_encode_macro.j2', 'failed': True}
fatal: [servername.com] => {'msg': 'AnsibleError: file: /ansible/roles/jtyr.grafana/templates/grafana.ini.j2, error: Cannot find/not allowed to load (include) template templates/encoder/macros/ini_encode_macro.j2', 'failed': True}
FATAL: all hosts have already failed -- aborting`

**Comment by jtyr** [comment]
Please can you show your template task and how and from where do you execute ansible-playbook?

**Comment by hgfranco** [comment]
This is how I'm running it:

```
ansible-playbook site.yml -i inventory/production -l server name.com -t grafana
```

Here's my site.yml:

```
- hosts: grafana
  roles:
    - { role: jtyr.grafana, tags: grafana }
```

Here's my current directory:

```
$ pwd:
/ansible
```

My template task is the same as you have it in your code:

```
- name: Configure Grafana
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini
  notify: Restart grafana
```

Here's what my grafana.ini.j2 file looks like:

```
#
# This file is managed by Ansible.
# Do not edit this file manually.
# Any changes will be automatically reverted.
#

{% from "templates/encoder/macros/ini_encode_macro.j2" import ini_encode with context -%}

{{ ini_encode(grafana_config, delimiter=" = ") }}
```

**Comment by jtyr** [comment]
OK. Did you download the [encoder macros](https://github.com/jtyr/config-encoder-macros). They should be on the same directory level like your playbook (`git clone https://github.com/picotrading/config-encoder-macros /ansible/templates/encoder`).

**Comment by hgfranco** [comment]
Ah I see. That wasn't clear in your README.md file. It's working now.
