### ISSUE TITLE
Update README.md with steps to address encoder macro error

### ISSUE THREAD

**Issue by andyfeller** [picotrading/ansible-grafana#6]
In [AnsibleError: file: grafana.ini.j2](https://github.com/picotrading/ansible-grafana/issues/4), a common setup error was discussed that required undocumented steps to address that are not listed within [ansible-grafana README.md](https://github.com/picotrading/ansible-grafana/blob/master/README.md) nor that it is a dependency.

Please update the project documentation to inform users about this dependency and the recommended way to incorporate as this isn't ansible-galaxy friendly.

**Comment by rathboma** [comment]
This has been open for over a year, can we just link to the issue in the readme?

**Comment by jtyr** [comment]
This role is obsolete. Please use [this](https://github.com/jtyr/ansible-grafana) instead.
